"""Commit the regenerated notes onto an agent branch and open/update its PR.

This is the only place the module mutates a remote, so it carries the push
discipline used elsewhere in the agent:

- Commits are authored as the bot (``BOT_NAME``/``BOT_EMAIL``) with no DCO
  sign-off -- a human must certify the notes before merge.
- The push target must live in the ``agent/release-notes/...`` namespace; any
  other branch is refused. (The backport allowlists are backport-only and would
  reject this branch, so we own and enforce our own prefix here.)
- Local git runs with the scrubbed, hook-disabled environment from
  :mod:`scripts.common.proc`; only the push carries the ``GitAuth`` credentials.

The branch is force-pushed with lease: this workflow fully owns its agent
branch, so a re-run replaces the generated commit rather than stacking commits,
and ``--force-with-lease`` still refuses to clobber an unexpected remote update.
The open PR (if any) is updated in place; otherwise a new one is created.
"""

from __future__ import annotations

import logging
from typing import Any, Sequence

from scripts.backport.pr_creator import build_pull_create_head_ref, build_pull_search_head_ref
from scripts.common.github_client import retry_github_call
from scripts.common.proc import BOT_EMAIL, BOT_NAME, run_git
from scripts.release_notes.models import MergedPR

logger = logging.getLogger(__name__)

BRANCH_PREFIX = "agent/release-notes"
NOTES_FILE = "00-RELEASENOTES"


def build_branch_name(head_ref: str) -> str:
    """Branch name for a release line, e.g. ``agent/release-notes/9.1``.

    Slashes in *head_ref* are flattened so the result is a single branch level
    under the prefix.
    """
    safe = head_ref.replace("/", "-")
    return f"{BRANCH_PREFIX}/{safe}"


def commit_and_push(
    repo_dir: str,
    *,
    branch: str,
    message: str,
    git_env: dict[str, str],
    file_rel: str = NOTES_FILE,
) -> None:
    """Configure the bot identity, commit *file_rel*, and push to *branch*.

    Refuses to push outside the ``agent/release-notes/`` namespace. The push is
    ``--force-with-lease`` to the named branch on ``origin`` (the cloned valkey
    remote).
    """
    if not branch.startswith(f"{BRANCH_PREFIX}/"):
        raise RuntimeError(
            f"Refusing to push to non-namespaced branch: {branch!r}. "
            f"Release-notes push targets must start with {BRANCH_PREFIX}/."
        )
    run_git(repo_dir, "config", "user.name", BOT_NAME)
    run_git(repo_dir, "config", "user.email", BOT_EMAIL)
    run_git(repo_dir, "checkout", "-B", branch)
    run_git(repo_dir, "add", file_rel)
    run_git(repo_dir, "commit", "-m", message)
    run_git(repo_dir, "push", "--force-with-lease", "origin", f"HEAD:{branch}", env=git_env)
    logger.info("Pushed regenerated %s to %s", file_rel, branch)


def find_existing_pr(repo: Any, *, base_repo: str, push_repo: str | None, branch: str) -> Any | None:
    """Return the open PR for *branch*, or None."""
    head_ref = build_pull_search_head_ref(base_repo, push_repo, branch)
    pulls = retry_github_call(
        lambda: list(repo.get_pulls(state="open", head=head_ref)),
        retries=3, description=f"search open PR for {head_ref}",
    )
    return pulls[0] if pulls else None


def open_or_update_pr(
    repo: Any,
    *,
    base_repo: str,
    push_repo: str | None,
    branch: str,
    base_branch: str,
    title: str,
    body: str,
    existing: Any | None,
) -> str:
    """Update *existing* PR in place, or create a new one. Returns the PR URL."""
    if existing is not None:
        retry_github_call(
            lambda: existing.edit(title=title, body=body),
            retries=3, description=f"update PR #{existing.number}",
        )
        logger.info("Updated release-notes PR #%s", existing.number)
        return existing.html_url
    head_ref = build_pull_create_head_ref(base_repo, push_repo, branch)
    pr = retry_github_call(
        lambda: repo.create_pull(title=title, body=body, head=head_ref, base=base_branch, draft=False),
        retries=3, description="create release-notes PR",
    )
    logger.info("Opened release-notes PR #%s", pr.number)
    return pr.html_url


def _escape_cell(text: str) -> str:
    """Escape a value for a Markdown table cell (pipes and newlines)."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def build_pr_body(
    *,
    base_tag: str,
    head_ref: str,
    included: int,
    skipped: Sequence[int],
    triage: Sequence[MergedPR],
) -> str:
    """Build the PR description, including a triage table of untagged PRs."""
    lines = [
        "Automated release-notes update generated by valkey-ci-agent.",
        "",
        f"- Release line: `{head_ref}`",
        f"- Baseline tag: `{base_tag}`",
        f"- Notes generated for **{included}** labelled PR(s).",
    ]
    if skipped:
        skipped_list = ", ".join(f"#{n}" for n in skipped)
        lines += ["", f"Skipped (no user-facing note): {skipped_list}"]
    if triage:
        lines += [
            "",
            "### Needs triage",
            "",
            "These merged PRs carry neither `release-notes` nor `no-release-notes` "
            "(or carry both) and were not included. A maintainer should label them:",
            "",
            "| PR | Title | Author |",
            "|----|-------|--------|",
        ]
        for pr in triage:
            author = f"@{pr.author}" if pr.author else "(unknown)"
            lines.append(f"| [#{pr.number}]({pr.url}) | {_escape_cell(pr.title)} | {author} |")
    lines += ["", "---", "*Generated by valkey-ci-agent. Review before merging.*"]
    return "\n".join(lines)


def publish(
    repo: Any,
    repo_dir: str,
    *,
    base_repo: str,
    push_repo: str | None,
    head_ref: str,
    base_branch: str,
    base_tag: str,
    included: int,
    skipped: Sequence[int],
    triage: Sequence[MergedPR],
    git_env: dict[str, str],
) -> str:
    """Commit, push, and open/update the release-notes PR. Returns the PR URL."""
    branch = build_branch_name(head_ref)
    title = f"Release notes for {head_ref} (since {base_tag})"
    body = build_pr_body(
        base_tag=base_tag, head_ref=head_ref, included=included, skipped=skipped, triage=triage,
    )
    commit_and_push(repo_dir, branch=branch, message=title, git_env=git_env)
    existing = find_existing_pr(repo, base_repo=base_repo, push_repo=push_repo, branch=branch)
    return open_or_update_pr(
        repo, base_repo=base_repo, push_repo=push_repo, branch=branch,
        base_branch=base_branch, title=title, body=body, existing=existing,
    )
